name: Push PR Branch

on:
  push:
    branches:
      - your-source-branch

permissions:
  contents: write
  pull-requests: write

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make some changes
        run: |
          echo "test change" >> test.txt
          git config user.name "actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "automated update" || echo "nothing to commit"

      - name: Push to feature branch
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/subhankar-iam/RIT-to-Karate.git
          git push origin HEAD:refs/heads/feature/2025 --force-with-lease
