name: Auto PR on Branch Push

on:
  push:
    branches:
      - 'feature/2025'

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Create PR if not exists
        run: |
          gh pr list --head "${{ github.ref_name }}" --base "release/2025" --json number --jq '.[0]' | grep -q null \
            && gh pr create --base release/2025 --head "${{ github.ref_name }}" \
                --title "Auto PR: ${{ github.ref_name }}" \
                --body "This PR was created automatically on push to `${{ github.ref_name }}`" \
            || echo "PR already exists."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
